version: "3"
services:
  hub:
    image: selenium/hub:4.27

  chrome:
    image: selenium/node-chromium:4.27
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1


  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    deploy:
      replicas: 1
    depends_on: 
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_VNC_NO_PASSWORD=1

  flightReservationPortal:
     image: selenium/docker100
     depends_on:
     - chrome
     environment:
     - BROWSER=chrome
     - HUB_HOST=hub
     - THREAD_COUNT=1
     - TEST_SUITE=FlightReservation.xml
     - CONFIG_PATH=/home/selenium-docker/config/global.properties
     volumes:
     - ./Results:/home/selenium-docker/test-output
  