version: "3"
services:
  hub:
    image: selenium/hub:4.27

  chrome:
    image: selenium/node-chromium:4.27
    shm_size: '2g'
    depends_on:
    - hub
    env_file: .env


  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2g'
    deploy:
      replicas: 1
    depends_on: 
    - hub
    env_file: .env

  flightReservationPortal:
     image: selenium/docker100
     depends_on:
     - chrome
     environment:
     - BROWSER=chrome
     - HUB_HOST=hub
     - THREAD_COUNT=1
     - TEST_SUITE=FlightReservation.xml
     - CONFIG_PATH=/home/selenium-docker/config/global.properties
     volumes:
     - ./Results:/home/selenium-docker/test-output
  