version: "3"
services:
   flightReservationPortal:
      image: apurvanaik422/seldocker100
      environment:
         - BROWSER
         - HUB_HOST=hub
         - THREAD_COUNT=1
         - TEST_SUITE=FlightReservation.xml
         - CONFIG_PATH=/home/selenium-docker/config/global.properties
      volumes:
         - ./Results:/home/selenium-docker/test-output

networks:
   default:
      external:
         name: seleniumdockerrunner_default